### ISSUE TITLE
Help: Issues with gunicorn behind nginx in docker environment

### ISSUE THREAD

**Issue by DanielCardonaRojas** [miguelgrinberg/Flask-SocketIO#565]
I have successfully incorporated flask-socketio into a project and runs fine with gunicorn and eventlet, it also works fine with docker-compose (celery rabbit and redis services). But when nginx is put in front of gunicorn, workers stop serving my regular api endpoints (get a 404, worker closes connection), even though socketio keeps working. I can imagine this is probably not a flask-socketio issue directly but I'm hoping to get some insight to figure this out.

Logs when querying a normal endpoint: 
```shell
api_1       | 2017-10-12 12:28:18 [7] [DEBUG] GET /api/users
api_1       | 2017-10-12 12:28:18 [7] [DEBUG] Closing connection.
```
These are the dependency versions:
- gunicorn==18.0
- Flask-SocketIO==2.9.2
- python-socketio==1.8.1
- python-engineio==1.7.0
- eventlet==0.21.0

Docker nginx image is version 1.12 > 1.4 and the nginx configuration file is mostly the same as the one you suggest.

```conf
upstream http_nodes {
    server api:5000; #Docker service name
}

upstream socketio_nodes {
    ip_hash;

    server api:5000; #Docker service name
}

server {
    listen 5000;
    server_name _;

    location / {
        proxy_pass http://http_nodes;
    }

    location /socket.io {
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://socketio_nodes/socket.io;
    }
}

```

This is docker-compose file im testing with:
```yaml
version: '3'
services:
    nginx:
        image: nginx:alpine
        ports: 
            - "5000:5000"
        volumes:
            - ./mobi-api.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - api
        restart: always
    postgres:
        image: mdillon/postgis
        volumes:
        - db_data:/var/lib/postgresql
        ports:
            - "5432"
        env_file: .env_postgres
    api:
        build: .
        #entrypoint: ./wait-for-it.sh postgres:5432 --
        volumes:
            - .:/api
        env_file: .env
        ports:
            - "5000"
        links:
            - postgres:postgres
        command: gunicorn wsgi:app --bind 0.0.0.0:5000 --worker-class eventlet --workers 1 --log-level DEBUG
        depends_on:
            - redis
            - postgres
            - rabbit
        restart: always

    celery:
        build: .
        volumes:
            - .:/api
        env_file: .env
        links: 
            - rabbit
            - postgres:postgres
        depends_on:
            - rabbit
        command: celery worker -A runcelery.celery --loglevel=info --host rabbit

    beat:
        build: .
        volumes:
            - .:/api
        env_file: .env
        links: 
            - celery
        depends_on:
            - celery
        command: celery beat -A runcelery.celery --loglevel=info

    rabbit:
        image: rabbitmq:3.6.12-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports: 
            - "5672"
    redis:
        image: redis:3.0-alpine
        ports: 
            - "6379"

            

volumes:
    db_data:
    static_files:

```

Any ideas on why this happens and how I could fix it?
Any other overall suggestions are welcome.
